version: 2
jobs:
  setup:
    docker:
      - image: circleci/ruby:2.6.5
    steps:
      - checkout
      - run: gem update --system
      - run: gem install bundler
      - run: bundle install --path vendor/bundle

  test:
    docker:
      - image: circleci/ruby:2.6.5
        environment:
          DATABASE_URL: postgresql://postgres:secret@localhost:5432/rails-pg-extras-test
      - image: circleci/postgres:11.5
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: rails-pg-extras-test
          POSTGRES_PASSWORD: secret
    parallelism: 1
    steps:
      - checkout
      - run: gem update --system
      - run: gem install bundler
      - run: bundle install --path vendor/bundle
      - run: sudo apt install postgresql-client
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Run specs
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | \
              circleci tests split --split-by=timings)"

            bundle exec rspec \
              --format progress \
              --format RspecJunitFormatter \
              --out /tmp/test-results/rspec.xml \
              --format progress \
              $TEST_FILES
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
workflows:
  version: 2
  setup_and_test:
    jobs:
      - setup
      - test:
          requires:
            - setup
